DefaultContentLanguage = "en"
baseurl = "/"
canonifyurls = true
disqusShortname = "shortname"
metaDataFormat = "toml"
paginate = 10
paginatePath = "page"
theme = "hugo-bootstrap-premium"
[Languages.en]
copyright = "(c) 2016 Copyright my blog"
languageCode = "en"
title = "My blog"
weight = 1
[[Languages.en.menu.footer]]
identifier = "disclaimer"
name = "Disclaimer"
pre = "<i>&middot;</i>"
url = "/disclaimer/"
weight = 1
[[Languages.en.menu.footer]]
identifier = "terms"
name = "Terms"
url = "/terms/"
weight = 2
[[Languages.en.menu.main]]
identifier = "post"
name = "Blog"
pre = ""
url = "/post/"
weight = 2
[[Languages.en.menu.main]]
identifier = ""
name = "About"
pre = "<i class='fa fa-road'></i>"
url = "https://appernetic.io/app/#/about"
weight = 1
[[Languages.en.menu.main]]
identifier = ""
name = "Dashboard"
url = "https://appernetic.io/app/"
weight = 3
[Languages.sv]
copyright = "(c) 2016 Alla rättigheter"
languageCode = "sv"
title = "Min blog"
weight = 2
[[Languages.sv.menu.footer]]
identifier = "friskrivning"
name = "Ansvarsfriskrivning"
pre = "<i>&middot;</i>"
url = "/sv/friskrivning/"
weight = 1
[[Languages.sv.menu.footer]]
identifier = "vilkor"
name = "Vilkor"
url = "/sv/vilkor/"
weight = 2
[[Languages.sv.menu.main]]
identifier = "post"
name = "Bloggen"
pre = ""
url = "/sv/post/"
weight = 2
[Languages.sv.taxonomies]
tag = "Taggar"
topic = "Ämne"
[author]
email = "yourname@example.com"
name = "yourname"
[blackfriday]
angledQuotes = true
extensionmask = []
extensions = []
fractions = false
hrefTargetBlank = false
latexDashes = true
plainIdAnchors = true
[params]
bitbucket = ""
bootswatchtheme = "paper"
brand = "My awsome blog"
brandimage = "http://blog.appernetic.io/images/apperneticlogo.png"
customcss = ["/css/style_custom.css"]
customjs = []
facebook = "Myprofile"
flattr = ""
footline = "code with <i class='fa fa-heart'></i>"
github = "Myprofile"
googleanalytics = "Your Google Analytics tracking code"
googleplus = "Myprofile"
highlight = "default"
home = "home"
linkedin = ""
mailmunchid = ""
mathjax = "2.7.1"
showrightsidebar = true
sumomeid = ""
switchlang = true
topline = "This is the best site ever"
twitter = "Myprofile"
youtube = ""
[params.popover]
cookiename = "mycookie1"
enablepopover = true
errormessage = "Submitting form failed!"
expirecookie = 5
headerimage = "//placehold.it/1000x600"
imagedescription = "Placeholder image for this popover modal optin form"
inputplaceholder = "Enter your email"
modalsize = ""
mouseleave = true
optin = true
posturl = "https://zapier.com/hooks/catch/1227563/"
showmodaltimeout = 10000
signupheader = "Join Our Newsletter"
signuptext = "Signup today for free and be the first to get notified on new updates."
submitbutton = "Subscribe"
successmessage = "Thanks for your subscription!"
[permalinks]
code = "/:filename/"
post = "/:year/:month/:day/:filename/"
[taxonomies]
tag = "tags"
topic = "topics"
